### ISSUE TITLE
Linking on names rather than ids

### ISSUE THREAD

**Issue by ZooeyMiller** [foundersandcoders/db-morning-challenge#10]
in the seconds exercise you have to link the tables together like this:
```sql
SELECT mentors.name, count (post_num) FROM mentors
INNER JOIN posts
ON mentors.name = posts.mentor_name
INNER JOIN likes
ON posts.num = likes.post_num
GROUP BY mentors.name;
```
We are joining on names, and then on post_num. 
Yesterday in our research we were led to believe that we should `INNER JOIN` on the IDs, not the names as those things can be variable, and joining on ID is then a consistent way for our databases to work. 

I just wanted to raise an issue because I found it a bit confusing to join in a way I had been led to believe was bad practice. 
(I may even have a wrong solution! Sorry if I'm wrong, just confused).

**Comment by ZooeyMiller** [comment]
Someone else just casted and showed this solution: 
```sql
SELECT posts.mentor_name, COUNT(likes.post_num) 
FROM likes INNER JOIN posts
ON likes.post_num = posts.num
GROUP BY posts.mentor_name
```
Which shows you don't need to link on name, but you do still link on "num" rather than "id" which I still find a wee bit confusing.

**Comment by shiryz** [comment]
@ZooeyMiller , you're right about it being good practice to put an id in the table as a primary key, but you can still join by any column you'd like and it doesn't have to be the id.

**Comment by shiryz** [comment]
Closing, this is now outdated
