### ISSUE TITLE
Suggest Heroku rather than ElephantSQL

### ISSUE THREAD

**Issue by ConchobarMacNessa** [foundersandcoders/db-morning-challenge#13]
My cohort (FAC10) ran into a number of issues using ElephantSQL (namely that it runs an older version of psql which doesn't include 'on confilct'.
I suggest switching from ElephantSQL to Heroku – many people on my course still felt uncomfortable hosting databases on heroku so I think it would be good to address this and teach it on the course.

**Comment by shiryz** [comment]
Changed to heroku via #12
