### ISSUE TITLE
Wrong column names in Readme

### ISSUE THREAD

**Issue by azayneeva** [foundersandcoders/db-morning-challenge#27]
<img width="624" alt="screen shot 2017-11-27 at 17 29 53" src="https://user-images.githubusercontent.com/24795752/33280019-9ddbc476-d398-11e7-863e-92624cf20fc1.png">
Column names wrongly including "num" rather than "id".

**Comment by astroash** [comment]
@azayneeva @RogeredBacon can this issue be closed?

**Comment by RogeredBacon** [comment]
Yup
